[[redirects]]
  from = "/posts/*"
  to = "/blog/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/writings/*"
  to = "/blog/:splat"
  status = 301
  force = true

[build]
  trailingSlash = "ignore"
